### ISSUE TITLE
Is it possible to upgrade to sweetalert 11.x?

### ISSUE THREAD

**Issue by gb5256** [zzbajie/yii2-sweetalert2#1]
Hi,
using this extension right now, but looks like it is using 9.x right now.
is it possible to upgrade to 11.x?

Thanks for letting me know if this is possible of not.

gb5256

**Comment by zzbajie** [comment]
surprise! Didn't expect anyone to use it.
Thank you for letting me know that there is a new version, I will consider upgrading in the near future, but not necessarily, I need time, thank you again!

**Comment by zzbajie** [comment]
> Hi, using this extension right now, but looks like it is using 9.x right now. is it possible to upgrade to 11.x?
> 
> Thanks for letting me know if this is possible of not.
> 
> gb5256

update completed！I wish you a happy use！
